import { useMemo, useState } from 'react'
import { ApartmentOutlined, CloudServerOutlined, DeleteOutlined, DownloadOutlined, EditOutlined, FileTextOutlined, GlobalOutlined, HomeOutlined, KeyOutlined, LockOutlined, PlusOutlined, ReloadOutlined, SafetyCertificateOutlined, SettingOutlined, TeamOutlined, UserOutlined } from '@ant-design/icons'
import { Alert, App as AntApp, Avatar, Badge, Button, Card, Col, ConfigProvider, Divider, Drawer, Dropdown, Empty, Flex, Form, Input, Layout, Menu, Modal, Popconfirm, Row, Segmented, Select, Space, Spin, Statistic, Switch, Table, Tag, Tooltip, Typography, message, theme } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import zhCN from 'antd/locale/zh_CN'
import enUS from 'antd/locale/en_US'
import './App.css'

type Network = { id:number; name:string; cidr:string; source:string; interface:string; gateway:string; enabled:boolean; reachable:boolean }
type Member = { id:number; name:string; enabled:boolean }
type GroupRef = { id:number; name:string; enabled:boolean }
type Group = { id:number; name:string; description:string; enabled:boolean; members:Member[]; allowedNetworks:Network[] }
type VPNUser = { id:number; name:string; certificateCN:string; staticIP:string; enabled:boolean; group:GroupRef; allowedNetworks:Network[] }
type Snapshot = { policyMode:string; vpnPool:string; xsrfToken:string; groups:Group[]; networks:Network[]; users:VPNUser[] }
type Section = 'overview'|'users'|'groups'|'matrix'|'networks'
type Editing = { kind:'user'; value:VPNUser|'new' }|{ kind:'group'; value:Group|'new' }|{ kind:'network'; value:Network|'new' }|null

const copy = {
  zh:{title:'OpenVPN 管理中心',sub:'身份、用户组与网络权限',overview:'权限总览',users:'VPN 用户',groups:'用户组',matrix:'权限矩阵',networks:'网络资源',management:'系统管理',dashboard:'运行概览',certificates:'证书管理',serverConfig:'服务端配置',logs:'运行日志',logout:'退出登录',deny:'默认拒绝',denyText:'只有启用的用户、用户组和已授权网络才能建立访问路径。',activeUsers:'启用用户',activeGroups:'启用用户组',activeNetworks:'启用网络',pool:'VPN 地址池',relation:'访问关系',relationHint:'从用户出发，直接查看所属组以及最终生效的网段。',addUser:'新建用户',addGroup:'新建用户组',addNetwork:'添加网络',discover:'发现主机网络',user:'用户',fixedIP:'固定 VPN IP',group:'所属用户组',allowed:'最终可访问网段',status:'状态',enabled:'启用',disabled:'停用',noAccess:'无访问权限',edit:'编辑',remove:'删除',renew:'更新证书',download:'下载 OVPN',members:'成员',permissions:'可访问网络',groupHint:'每个用户只属于一个组；用户组统一决定成员能够访问哪些网段。',matrixHint:'开关表示用户组与网段的授权关系，修改后立即重算访问策略。',network:'网络',source:'来源',iface:'网卡',usedBy:'授权给',reachable:'可达',manual:'手动',auto:'自动发现',save:'保存',cancel:'取消',name:'名称',description:'描述',cn:'证书 CN',autoIP:'留空则自动分配',selectGroup:'选择用户组',loading:'正在读取权限关系…',search:'搜索用户、证书或 IP',allGroups:'全部用户组',allStatus:'全部状态',configured:'已授权',noMembers:'暂无成员'},
  en:{title:'OpenVPN Console',sub:'Identities, groups and network access',overview:'Overview',users:'VPN users',groups:'Groups',matrix:'Permission matrix',networks:'Networks',management:'System management',dashboard:'Dashboard',certificates:'Certificates',serverConfig:'Server configuration',logs:'Logs',logout:'Sign out',deny:'Default deny',denyText:'A path is allowed only when the user, group and assigned network are enabled.',activeUsers:'Active users',activeGroups:'Active groups',activeNetworks:'Enabled networks',pool:'VPN pool',relation:'Access relationships',relationHint:'Start with a user and see the group and effective networks in one place.',addUser:'New user',addGroup:'New group',addNetwork:'Add network',discover:'Discover host networks',user:'User',fixedIP:'Fixed VPN IP',group:'Group',allowed:'Effective networks',status:'Status',enabled:'Enabled',disabled:'Disabled',noAccess:'No access',edit:'Edit',remove:'Delete',renew:'Renew certificate',download:'Download OVPN',members:'Members',permissions:'Allowed networks',groupHint:'A user belongs to one group. The group controls every member’s network access.',matrixHint:'Each switch is a group-to-network grant. Changes immediately rebuild the access policy.',network:'Network',source:'Source',iface:'Interface',usedBy:'Used by',reachable:'Reachable',manual:'Manual',auto:'Discovered',save:'Save',cancel:'Cancel',name:'Name',description:'Description',cn:'Certificate CN',autoIP:'Leave blank for automatic allocation',selectGroup:'Select a group',loading:'Loading access relationships…',search:'Search user, certificate or IP',allGroups:'All groups',allStatus:'All statuses',configured:'Granted',noMembers:'No members'}
} as const

async function load():Promise<Snapshot>{const r=await fetch('/api/v1/access',{credentials:'same-origin'});if(r.status===401){location.href='/login';throw new Error('authentication required')}if(!r.ok)throw new Error(await r.text());return r.json()}

function Console(){
  const [lang,setLang]=useState<'zh'|'en'>(()=>(localStorage.getItem('openvpn-ui-language') as 'zh'|'en')||'zh')
  const [section,setSection]=useState<Section>('overview'),[editing,setEditing]=useState<Editing>(null),[search,setSearch]=useState(''),[groupFilter,setGroupFilter]=useState<number|'all'>('all'),[statusFilter,setStatusFilter]=useState<'all'|'enabled'|'disabled'>('all')
  const [form]=Form.useForm(), t=copy[lang], qc=useQueryClient(), query=useQuery({queryKey:['access'],queryFn:load}), data=query.data
  const action=useMutation({mutationFn:async({name,values={}}:{name:string;values?:Record<string,unknown>})=>{if(!data)throw new Error('not loaded');const body=new URLSearchParams({action:name,_xsrf:data.xsrfToken});Object.entries(values).forEach(([k,v])=>{if(Array.isArray(v))v.forEach(x=>body.append(k,String(x)));else if(typeof v==='boolean'){if(v)body.append(k,'on')}else if(v!==undefined&&v!==null)body.append(k,String(v))});const r=await fetch('/access',{method:'POST',body,credentials:'same-origin',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(await r.text())},onSuccess:async()=>{await qc.invalidateQueries({queryKey:['access']});message.success(lang==='zh'?'已保存':'Saved')},onError:e=>message.error(e.message)})
  const tags=(items:Network[])=>items.length?<Space size={[4,5]} wrap>{items.map(n=><Tag key={n.id} color={n.enabled?'cyan':'default'}>{n.name}<span className="cidr">{n.cidr}</span></Tag>)}</Space>:<span className="muted">{t.noAccess}</span>
  const open=(next:Editing)=>{setEditing(next);form.resetFields();if(!next)return;if(next.value==='new'){form.setFieldsValue({Enabled:true,NetworkIDs:[]});return}if(next.kind==='user'){const v=next.value;form.setFieldsValue({Name:v.name,CertificateCN:v.certificateCN,StaticIP:v.staticIP,GroupId:v.group.id,Enabled:v.enabled})}if(next.kind==='group'){const v=next.value;form.setFieldsValue({Name:v.name,Description:v.description,Enabled:v.enabled,NetworkIDs:v.allowedNetworks.map(n=>n.id)})}if(next.kind==='network'){const v=next.value;form.setFieldsValue({Name:v.name,CIDR:v.cidr,Enabled:v.enabled})}}
  const submit=async(values:Record<string,unknown>)=>{if(!editing)return;const fresh=editing.value==='new';const id=editing.value==='new'?undefined:editing.value.id;await action.mutateAsync({name:`${fresh?'create':'update'}-${editing.kind}`,values:{...values,Id:id}});setEditing(null)}
  const filtered=useMemo(()=>(data?.users||[]).filter(u=>(groupFilter==='all'||u.group.id===groupFilter)&&(statusFilter==='all'||u.enabled===(statusFilter==='enabled'))&&(!search||`${u.name} ${u.certificateCN} ${u.staticIP}`.toLowerCase().includes(search.toLowerCase()))),[data,groupFilter,statusFilter,search])
  if(query.isLoading||!data)return <div className="loading"><Spin size="large"/><span>{t.loading}</span></div>
  if(query.error)return <div className="loading"><Alert type="error" showIcon message={query.error.message}/></div>
  const usersCols:ColumnsType<VPNUser>=[
    {title:t.user,key:'user',width:210,render:(_,u)=><Flex align="center" gap={10}><Avatar className="avatar" icon={<UserOutlined/>}/><div><strong>{u.name}</strong><small>{u.certificateCN}</small></div></Flex>},
    {title:t.fixedIP,dataIndex:'staticIP',width:140,render:v=><Typography.Text code>{v}</Typography.Text>},{title:t.group,key:'group',width:170,render:(_,u)=><Tag color={u.group.enabled?'geekblue':'default'} icon={<TeamOutlined/>}>{u.group.name}</Tag>},
    {title:t.allowed,key:'allowed',render:(_,u)=>tags(u.allowedNetworks)},{title:t.status,key:'status',width:90,render:(_,u)=><Badge status={u.enabled?'success':'default'} text={u.enabled?t.enabled:t.disabled}/ >},
    {title:'',key:'actions',width:120,fixed:'right',render:(_,u)=><Space size={1}><Tooltip title={t.download}><Button type="text" icon={<DownloadOutlined/>} href={`/certificates/${encodeURIComponent(u.certificateCN)}`}/></Tooltip><Dropdown menu={{items:[{key:'edit',icon:<EditOutlined/>,label:t.edit,onClick:()=>open({kind:'user',value:u})},{key:'renew',icon:<ReloadOutlined/>,label:t.renew,onClick:()=>Modal.confirm({title:t.renew,content:lang==='zh'?'旧证书会立即吊销，请重新下载 OVPN 文件。':'The old certificate is revoked immediately. Download a new OVPN file.',onOk:()=>action.mutateAsync({name:'renew-user',values:{Id:u.id}})})},{type:'divider'},{key:'delete',danger:true,icon:<DeleteOutlined/>,label:t.remove,onClick:()=>Modal.confirm({title:lang==='zh'?'删除用户并吊销证书？':'Delete user and revoke certificate?',okButtonProps:{danger:true},onOk:()=>action.mutateAsync({name:'delete-user',values:{Id:u.id}})})}]}}><Button type="text">•••</Button></Dropdown></Space>}
  ]
  const overview=<><Row gutter={[16,16]}><Col xs={24} sm={12} xl={6}><Card className="metric"><Statistic title={t.activeUsers} value={data.users.filter(x=>x.enabled).length} suffix={`/ ${data.users.length}`} prefix={<UserOutlined/>}/></Card></Col><Col xs={24} sm={12} xl={6}><Card className="metric"><Statistic title={t.activeGroups} value={data.groups.filter(x=>x.enabled).length} suffix={`/ ${data.groups.length}`} prefix={<TeamOutlined/>}/></Card></Col><Col xs={24} sm={12} xl={6}><Card className="metric"><Statistic title={t.activeNetworks} value={data.networks.filter(x=>x.enabled).length} suffix={`/ ${data.networks.length}`} prefix={<CloudServerOutlined/>}/></Card></Col><Col xs={24} sm={12} xl={6}><Card className="metric"><Statistic title={t.pool} value={data.vpnPool||"—"} prefix={<GlobalOutlined/>}/></Card></Col></Row><Card className="panel relationships" title={<Space><ApartmentOutlined/>{t.relation}</Space>} extra={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>open({kind:"user",value:"new"})}>{t.addUser}</Button>}><Typography.Paragraph type="secondary">{t.relationHint}</Typography.Paragraph>{data.users.map(u=><div className="relation" key={u.id}><div className="person"><Avatar icon={<UserOutlined/>}/><div><strong>{u.name}</strong><small>{u.staticIP}</small></div></div><i/><Tag color={u.group.enabled?"geekblue":"default"} icon={<TeamOutlined/>}>{u.group.name}</Tag><i/><div>{tags(u.allowedNetworks)}</div></div>)}{!data.users.length&&<Empty image={Empty.PRESENTED_IMAGE_SIMPLE}/>}</Card></>
  const users=<Card className="panel" title={t.users} extra={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>open({kind:'user',value:'new'})}>{t.addUser}</Button>}><Flex className="toolbar" gap={10} wrap><Input.Search allowClear placeholder={t.search} onChange={e=>setSearch(e.target.value)}/><Select value={groupFilter} onChange={setGroupFilter} options={[{value:'all',label:t.allGroups},...data.groups.map(g=>({value:g.id,label:g.name}))]}/><Select value={statusFilter} onChange={setStatusFilter} options={[{value:'all',label:t.allStatus},{value:'enabled',label:t.enabled},{value:'disabled',label:t.disabled}]}/></Flex><Table rowKey="id" columns={usersCols} dataSource={filtered} scroll={{x:1000}}/></Card>
  const groups=<><Alert className="hint" type="info" showIcon message={t.groupHint}/><div className="groups">{data.groups.map(g=><Card className="group-card" key={g.id} title={<Space><Avatar size="small" icon={<TeamOutlined/>}/>{g.name}{!g.enabled&&<Tag>{t.disabled}</Tag>}</Space>} extra={<Dropdown menu={{items:[{key:'edit',icon:<EditOutlined/>,label:t.edit,onClick:()=>open({kind:'group',value:g})},{key:'delete',danger:true,disabled:g.members.length>0,icon:<DeleteOutlined/>,label:t.remove,onClick:()=>action.mutate({name:'delete-group',values:{Id:g.id}})}]}}><Button type="text">•••</Button></Dropdown>}><Typography.Paragraph type="secondary" className="description">{g.description||'—'}</Typography.Paragraph><Divider plain>{t.members} · {g.members.length}</Divider><Space wrap>{g.members.length?g.members.map(m=><Tag key={m.id} color={m.enabled?'blue':'default'} icon={<UserOutlined/>}>{m.name}</Tag>):<span className="muted">{t.noMembers}</span>}</Space><Divider plain>{t.permissions} · {g.allowedNetworks.length}</Divider>{tags(g.allowedNetworks)}</Card>)}<button className="new-card" onClick={()=>open({kind:'group',value:'new'})}><PlusOutlined/><span>{t.addGroup}</span></button></div></>
  const matrix=<Card className="panel" title={t.matrix}><Alert className="hint" type="info" showIcon message={t.matrixHint}/><div className="matrix-scroll"><table className="matrix"><thead><tr><th>{t.groups} / {t.networks}</th>{data.networks.map(n=><th key={n.id}>{n.name}<code>{n.cidr}</code></th>)}</tr></thead><tbody>{data.groups.map(g=><tr key={g.id}><td><strong>{g.name}</strong><small>{g.members.length} {t.members}</small></td>{data.networks.map(n=>{const checked=g.allowedNetworks.some(x=>x.id===n.id);return <td key={n.id}><Switch checked={checked} loading={action.isPending} onChange={on=>{const ids=g.allowedNetworks.map(x=>x.id).filter(id=>id!==n.id);if(on)ids.push(n.id);action.mutate({name:'update-group',values:{Id:g.id,Name:g.name,Description:g.description,Enabled:g.enabled,NetworkIDs:ids}})}}/><small className={checked?'on':''}>{checked?t.configured:'—'}</small></td>})}</tr>)}</tbody></table></div></Card>
  const netCols:ColumnsType<Network>=[{title:t.network,key:'network',render:(_,n)=><div><strong>{n.name}</strong><small><Typography.Text code>{n.cidr}</Typography.Text></small></div>},{title:t.source,key:'source',width:120,render:(_,n)=><Tag color={n.source==='manual'?'purple':'cyan'}>{n.source==='manual'?t.manual:t.auto}</Tag>},{title:t.iface,dataIndex:'interface',width:120,render:v=>v||'—'},{title:t.usedBy,key:'groups',render:(_,n)=><Space wrap>{data.groups.filter(g=>g.allowedNetworks.some(x=>x.id===n.id)).map(g=><Tag key={g.id} icon={<TeamOutlined/>}>{g.name}</Tag>)}</Space>},{title:t.status,key:'status',width:100,render:(_,n)=><Badge status={n.enabled?'success':'default'} text={n.enabled?t.enabled:t.disabled}/>},{title:'',key:'action',width:90,render:(_,n)=><Space><Button type="text" icon={<EditOutlined/>} onClick={()=>open({kind:'network',value:n})}/><Popconfirm title={lang==='zh'?'删除这个网络？':'Delete this network?'} onConfirm={()=>action.mutate({name:'delete-network',values:{Id:n.id}})}><Button danger type="text" icon={<DeleteOutlined/>}/></Popconfirm></Space>}]
  const networks=<Card className="panel" title={t.networks} extra={<Space><Button icon={<ReloadOutlined/>} onClick={()=>action.mutate({name:'discover-networks'})}>{t.discover}</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>open({kind:'network',value:'new'})}>{t.addNetwork}</Button></Space>}><Table rowKey="id" columns={netCols} dataSource={data.networks} scroll={{x:850}} pagination={false}/></Card>
  const content={overview,users,groups,matrix,networks}[section]
  const drawerTitle=editing?.kind==='user'?t.addUser:editing?.kind==='group'?t.addGroup:t.addNetwork
  return <Layout className="shell"><Layout.Sider width={244} breakpoint="lg" collapsedWidth={0} className="sider"><a className="brand" href="/"><b><img src="/static/img/openvpn-win.svg" alt=""/></b><div><strong>OpenVPN</strong><small>{lang==='zh'?'管理控制台':'Management console'}</small></div></a><div className="menu-caption">{lang==='zh'?'访问控制':'Access control'}</div><Menu theme="dark" selectedKeys={[section]} onClick={({key})=>setSection(key as Section)} items={[{key:'overview',icon:<ApartmentOutlined/>,label:t.overview},{key:'users',icon:<UserOutlined/>,label:t.users},{key:'groups',icon:<TeamOutlined/>,label:t.groups},{key:'matrix',icon:<KeyOutlined/>,label:t.matrix},{key:'networks',icon:<CloudServerOutlined/>,label:t.networks}]}/><div className="console-links"><div className="menu-caption">{t.management}</div><a href="/"><HomeOutlined/>{t.dashboard}</a><a href="/certificates"><SafetyCertificateOutlined/>{t.certificates}</a><a href="/ov/config"><SettingOutlined/>{t.serverConfig}</a><a href="/logs"><FileTextOutlined/>{t.logs}</a></div><div className="sider-foot"><Button type="link" href="/logout">{t.logout}</Button></div></Layout.Sider><Layout><Layout.Header className="header"><div><Typography.Title level={4}>{t.title}</Typography.Title><Typography.Text type="secondary">{t.sub}</Typography.Text></div><Space><Tag className="deny" icon={<LockOutlined/>}>{t.deny}</Tag><Segmented size="small" value={lang} options={[{label:'中文',value:'zh'},{label:'EN',value:'en'}]} onChange={v=>{localStorage.setItem('openvpn-ui-language',v as string);setLang(v as 'zh'|'en')}}/></Space></Layout.Header><Layout.Content className="content"><Alert className="policy" type="success" showIcon message={t.denyText}/>{content}</Layout.Content></Layout>
    <Drawer width={480} title={drawerTitle} open={!!editing} onClose={()=>setEditing(null)} destroyOnHidden extra={<Space><Button onClick={()=>setEditing(null)}>{t.cancel}</Button><Button type="primary" loading={action.isPending} onClick={()=>form.submit()}>{t.save}</Button></Space>}><Form form={form} layout="vertical" onFinish={submit}>{editing?.kind==='user'&&<><Form.Item label={t.name} name="Name" rules={[{required:true}]}><Input/></Form.Item><Form.Item label={t.cn} name="CertificateCN" rules={[{required:editing.value==='new',pattern:/^[A-Za-z0-9_.@-]+$/}]}><Input disabled={editing.value!=='new'}/></Form.Item><Form.Item label={t.fixedIP} name="StaticIP"><Input placeholder={t.autoIP}/></Form.Item><Form.Item label={t.group} name="GroupId" rules={[{required:true}]}><Select placeholder={t.selectGroup} options={data.groups.map(g=>({value:g.id,label:g.name,disabled:!g.enabled}))}/></Form.Item>{editing.value!=='new'&&<Form.Item label={t.status} name="Enabled" valuePropName="checked"><Switch/></Form.Item>}</>}{editing?.kind==='group'&&<><Form.Item label={t.name} name="Name" rules={[{required:true}]}><Input/></Form.Item><Form.Item label={t.description} name="Description"><Input.TextArea rows={3}/></Form.Item>{editing.value!=='new'&&<Form.Item label={t.status} name="Enabled" valuePropName="checked"><Switch/></Form.Item>}<Form.Item label={t.permissions} name="NetworkIDs"><Select mode="multiple" options={data.networks.map(n=>({value:n.id,label:`${n.name} · ${n.cidr}`}))}/></Form.Item></>}{editing?.kind==='network'&&<><Form.Item label={t.name} name="Name"><Input/></Form.Item><Form.Item label="IPv4 CIDR" name="CIDR" rules={[{required:editing.value==='new'}]}><Input disabled={editing.value!=='new'} placeholder="192.168.18.0/24"/></Form.Item>{editing.value!=='new'&&<Form.Item label={t.status} name="Enabled" valuePropName="checked"><Switch/></Form.Item>}</>}</Form></Drawer>
  </Layout>
}

const queryClient=new QueryClient()
export default function App(){const isEnglish=localStorage.getItem('openvpn-ui-language')==='en';return <ConfigProvider locale={isEnglish?enUS:zhCN} theme={{algorithm:theme.defaultAlgorithm,token:{colorPrimary:'#2864dc',borderRadius:10,colorBgLayout:'#f5f7fb',fontFamily:"Inter,'Segoe UI','PingFang SC',sans-serif"}}}><AntApp><QueryClientProvider client={queryClient}><Console/></QueryClientProvider></AntApp></ConfigProvider>}
